FROM ghcr.io/linuxserver/baseimage-alpine:arm32v7-3.15
RUN apk update && apk add --update ca-certificates \
    cmake make automake autoconf \
    pkgconfig curl-dev libevent-dev gcc \
    g++ git gettext-dev linux-headers